stages:
  - build:rpm
  - build:dockerimage
  - test
  - publish

before_script:
  - source gitlab-ci/export_branch.sh
  - echo "Exporting BRANCH=${BRANCH}"

eos_rpm_cc7:
  stage: build:rpm
  image: gitlab-registry.cern.ch/linuxsupport/cc7-base
  script:
    - yum install --nogpg -y gcc-c++ cmake3 make rpm-build which git yum-plugin-priorities ccache epel-release
    - git submodule update --init --recursive
    - mkdir build
    - cd build
    - cmake3 .. -DPACKAGEONLY=1
    - make srpm
    - cd ..
    - source gitlab-ci/export_buildtype.sh 24 build/SRPMS
    - if [ "$BUILD_TYPE" == "commit" ]; then source gitlab-ci/setup_ccache.sh; else export CCACHE_DISABLE=1; fi
    - echo -e '[eos-depend]\nname=EOS dependencies\nbaseurl=http://storage-ci.web.cern.ch/storage-ci/eos/'${BRANCH}'-depend/el-7/x86_64/\ngpgcheck=0\nenabled=1\nexclude=xrootd*\npriority=4\n' >> /etc/yum.repos.d/eos-depend.repo
    - echo -e '\n[kio]\nname=kio\nbaseurl=https://dss-ci-repo.web.cern.ch/dss-ci-repo/kinetic/kineticio/el-7-x86_64\nenabled=1\n' >> /etc/yum.repos.d/eos-depend.repo
    - yum-builddep --nogpgcheck -y build/SRPMS/*
    - rpmbuild --rebuild --with=server --define "_rpmdir build/RPMS/" --define "_build_name_fmt %%{NAME}-%%{VERSION}-%%{RELEASE}.%%{ARCH}.rpm" build/SRPMS/*
    - ccache -s
    - mkdir cc7_artifacts
    - cp -R build/SRPMS cc7_artifacts
    - cp -R build/RPMS cc7_artifacts
    - git clone https://gitlab.cern.ch/eos/eos-docker.git
    - echo -e '[eos-depend]\nname=EOS dependencies \nbaseurl=http://storage-ci.web.cern.ch/storage-ci/eos/'${BRANCH}'-depend/el-7/x86_64/\ngpgcheck=0\nenabled=1\npriority=4\n' > eos-docker/eos.repo
    # TODO: this repository needs to be removed in the future
    - echo -e '[eos-depend-afs]\nname=EOS dependencies on AFS\nbaseurl=http://dss-ci-repo.web.cern.ch/dss-ci-repo/eos/'${BRANCH}'-depend/el-7-x86_64/\ngpgcheck=0\nenabled=1\npriority=4\n' >> eos-docker/eos.repo
  cache:
    key: "$CI_BUILD_NAME/$CI_BUILD_REF_NAME"
    paths:
    - ccache/
  artifacts:
    expire_in: 1 day
    paths:
    - cc7_artifacts/
    - eos-docker/
  tags:
    - docker-cc7
  only:
    - master
    - beryl_aquamarine

eos_rpm_slc6:
  stage: build:rpm
  image: gitlab-registry.cern.ch/linuxsupport/slc6-base
  script:
    - yum install --nogpg -y gcc-c++ cmake3 make rpm-build which git yum-plugin-priorities tar ccache
    - git submodule update --init --recursive
    - mkdir build
    - cd build
    - cmake3 .. -DPACKAGEONLY=1
    - make srpm
    - cd ..
    - source gitlab-ci/export_buildtype.sh 24 build/SRPMS
    - if [ "$BUILD_TYPE" == "commit" ]; then source gitlab-ci/setup_ccache_slc6.sh; ccache --max-size=1.5G; else export CCACHE_DISABLE=1; fi
    - echo -e '[eos-depend]\nname=EOS dependencies\nbaseurl=http://storage-ci.web.cern.ch/storage-ci/eos/'${BRANCH}'-depend/el-6/x86_64/\ngpgcheck=0\nenabled=1\nexclude=xrootd*\npriority=4\n' >> /etc/yum.repos.d/eos-depend.repo
    # TODO: this repository needs to be removed in the future
    - echo -e '\n[kio]\nname=kio\nbaseurl=https://dss-ci-repo.web.cern.ch/dss-ci-repo/kinetic/kineticio/el-6-x86_64\nenabled=1\n' >> /etc/yum.repos.d/eos-depend.repo
    - yum-builddep --nogpgcheck -y build/SRPMS/*
    - rpmbuild --rebuild --with server --define "_rpmdir build/RPMS/" --define "_build_name_fmt %%{NAME}-%%{VERSION}-%%{RELEASE}.%%{ARCH}.rpm" build/SRPMS/*
    - ccache -s
    - mkdir slc6_artifacts
    - cp -R build/SRPMS slc6_artifacts
    - cp -R build/RPMS slc6_artifacts
  cache:
    key: "$CI_BUILD_NAME/$CI_BUILD_REF_NAME"
    paths:
    - ccache/
  artifacts:
    expire_in: 1 day
    paths:
    - slc6_artifacts/
  tags:
    - docker-slc6
  only:
    - master
    - beryl_aquamarine

eos_rpm_fedora_rawhide:
  stage: build:rpm
  image: fedora:rawhide
  script:
    - dnf install --nogpg -y gcc-c++ cmake3 make rpm-build which git yum-plugin-priorities tar yum-utils ccache https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    - git submodule update --init --recursive
    - mkdir build
    - cd build
    - cmake3 .. -DPACKAGEONLY=1
    - make srpm
    - cd ..
    - source gitlab-ci/export_buildtype.sh 25 build/SRPMS
    - if [ "$BUILD_TYPE" == "commit" ]; then source gitlab-ci/setup_ccache_fc.sh; else export CCACHE_DISABLE=1; fi
    - echo -e '[eos-depend]\nname=EOS dependencies\nbaseurl=http://storage-ci.web.cern.ch/storage-ci/eos/'${BRANCH}'-depend/fc-rawhide/x86_64/\ngpgcheck=0\nenabled=1\nexclude=xrootd*\npriority=4\n' >> /etc/yum.repos.d/eos-depend.repo
    - yum-builddep --nogpgcheck -y build/SRPMS/*
    - rpmbuild --rebuild --with server --define "_rpmdir build/RPMS/" --define "_build_name_fmt %%{NAME}-%%{VERSION}-%%{RELEASE}.%%{ARCH}.rpm" build/SRPMS/*
    - ccache -s
    - mkdir fcrawhide_artifacts
    - cp -R build/SRPMS fcrawhide_artifacts
    - cp -R build/RPMS fcrawhide_artifacts
  cache:
    key: "$CI_BUILD_NAME/$CI_BUILD_REF_NAME"
    paths:
    - ccache/
  artifacts:
    expire_in: 1 day
    paths:
    - fcrawhide_artifacts/
  tags:
    - docker-fc_rawhide
  allow_failure: true
  only:
    - master

eos_rpm_fedora_25:
  stage: build:rpm
  image: fedora:25
  script:
    - dnf install --nogpg -y gcc-c++ cmake3 make rpm-build which git yum-plugin-priorities tar yum-utils ccache https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    - git submodule update --init --recursive
    - mkdir build
    - cd build
    - cmake3 .. -DPACKAGEONLY=1
    - make srpm
    - cd ..
    - source gitlab-ci/export_buildtype.sh 24 build/SRPMS
    - if [ "$BUILD_TYPE" == "commit" ]; then source gitlab-ci/setup_ccache_fc.sh; else export CCACHE_DISABLE=1; fi
    - echo -e '[eos-depend]\nname=EOS dependencies\nbaseurl=http://storage-ci.web.cern.ch/storage-ci/eos/'${BRANCH}'-depend/fc-25/x86_64/\ngpgcheck=0\nenabled=1\nexclude=xrootd*\npriority=4\n' >> /etc/yum.repos.d/eos-depend.repo
    - yum-builddep --nogpgcheck -y build/SRPMS/*
    - rpmbuild --rebuild --with server --define "_rpmdir build/RPMS/" --define "_build_name_fmt %%{NAME}-%%{VERSION}-%%{RELEASE}.%%{ARCH}.rpm" build/SRPMS/*
    - ccache -s
    - mkdir fcold_artifacts
    - cp -R build/SRPMS fcold_artifacts
    - cp -R build/RPMS fcold_artifacts
  cache:
    key: "$CI_BUILD_NAME/$CI_BUILD_REF_NAME"
    paths:
    - ccache/
  artifacts:
    expire_in: 1 day
    paths:
    - fcold_artifacts/
  tags:
    - docker-fc25
  allow_failure: true
  only:
    - master

eos_dmg_macosx:
  stage: build:rpm
  script:
    - git submodule update --init --recursive
    - mkdir build
    - mkdir install
    - cd build
    - /Users/jenkins/workspace/cmake-3.5.2/install/bin/cmake -DCLIENT=1 -DCMAKE_INSTALL_PREFIX=/usr/local -D Z_ROOT_DIR=/usr/local/opt/zlib/ -D OPENSSL_ROOT_DIR=/usr/local/opt/openssl/ -D NCURSES_ROOT_DIR=/usr/local/opt/ncurses/ -D ZMQ_ROOT_DIR=/usr/local/opt/zeromq32/ -D XROOTD_ROOT_DIR=/usr/local/opt/xrootd/ ..
    - make -j 4
    - make install DESTDIR=../install/
    - version=`../genversion.sh`
    - ../utils/eos-osx-package.sh $version ../install/
    - ccache -s
    - cd ..
    - mkdir osx_artifacts
    - cp build/*.dmg osx_artifacts
  artifacts:
    expire_in: 1 day
    paths:
    - osx_artifacts/
  tags:
    - macosx-shell
  allow_failure: true
  only:
    - master

eos_docker:
  stage: build:dockerimage
  tags:
    - docker-image-build
  script:
    - ""
  variables:
    TO: gitlab-registry.cern.ch/dss/eos:${CI_PIPELINE_ID}
    DOCKER_FILE: eos-docker/Dockerfile
  dependencies:
    - eos_rpm_cc7
  only:
    - master
    - beryl_aquamarine

eos_system_test:
  stage: test
  script:
    - sudo ./eos-docker/scripts/shutdown_services.sh
    - ./eos-docker/scripts/remove_unused_images.sh
    - docker pull gitlab-registry.cern.ch/dss/eos:${CI_PIPELINE_ID}
    - sudo ./eos-docker/scripts/start_services.sh -i gitlab-registry.cern.ch/dss/eos:${CI_PIPELINE_ID}
    - docker exec -i eos-mgm-test eos chmod 2777 /eos/dockertest
    - docker exec -i eos-client-test git clone https://gitlab.cern.ch/dss/eosclient-tests.git
    - docker exec -i eos-client-test env EOS_MGM_URL=root://eos-mgm-test.eoscluster.cern.ch eos fuse mount /eos
    - docker exec -i eos-client-test python /eosclient-tests/microtests/run-ci.py --eosdir /eos/dockertest
    - docker exec -i eos-mgm-test eos-instance-test-ci
    - sudo ./eos-docker/scripts/shutdown_services.sh
    - docker rmi gitlab-registry.cern.ch/dss/eos:${CI_PIPELINE_ID}
  tags:
    - shell-with-docker
  dependencies:
    - eos_rpm_cc7
  only:
    - master
    - master-ci

eos_stress_test:
  stage: test
  script:
    - sudo ./eos-docker/scripts/shutdown_services.sh
    - ./eos-docker/scripts/remove_unused_images.sh
    - docker pull gitlab-registry.cern.ch/dss/eos:${CI_PIPELINE_ID}
    - sudo ./eos-docker/scripts/start_services.sh -i gitlab-registry.cern.ch/dss/eos:${CI_PIPELINE_ID}
    - docker exec -i eos-mgm-test eos chmod 2777 /eos/dockertest
    - docker exec -i eos-mgm-test hammer-runner.py --strict-exit-code 1 --url eos-mgm-test.eoscluster.cern.ch//eos/dockertest/hammer/ --protocols xroot --threads 1 2 10 100 --operations write stat read delete --runs 3 --nfiles 10000
    - sudo ./eos-docker/scripts/shutdown_services.sh
    - docker rmi gitlab-registry.cern.ch/dss/eos:${CI_PIPELINE_ID}
  tags:
    - eos-stress
  dependencies:
    - eos_rpm_cc7
  allow_failure: true
  only:
    - master
    - master-ci

eos_publish_artifacts:
  stage: publish
  image: gitlab-registry.cern.ch/linuxsupport/cc7-base
  script:
    - yum install --nogpg -y sssd-client sudo createrepo
    - echo "Publishing `find cc7_artifacts -name 'eos-*.src.rpm' -print0`"
    - source gitlab-ci/export_buildtype.sh 24 cc7_artifacts
    - if [ "$BUILD_TYPE" == "tag" ]; then ./gitlab-ci/store_artifacts.sh ${BRANCH} ${BUILD_TYPE} /mnt/eos_repositories/eos; fi
    - sudo -u stci -H ./gitlab-ci/store_artifacts.sh ${BRANCH} ${BUILD_TYPE} /eos/project/s/storage-ci/www/eos
    - sudo -u stci -H ./gitlab-ci/remove_old_artifacts.sh
  tags:
    - docker-cc7
  only:
    - master
    - beryl_aquamarine

eos_periodic_coverity:
  stage: build:rpm
  script:
    - git submodule update --init --recursive
    - mkdir build
    - cd build
    - cmake3 .. -DPACKAGEONLY=1
    - make srpm
    - sudo yum-builddep --nogpgcheck -y SRPMS/*
    - rm -f CMakeCache.txt
    - cmake3 ..
    - cov-build --dir cov-int make -j 4
    - tar czvf eos-metrics.tgz cov-int
    - curl --form token="`cat /home/gitlab-runner/.coverity_token`" --form email=project-eos-commits@cern.ch --form file=@eos-metrics.tgz --form version="`../genversion.sh`" --form description="Periodic Gitlab build" https://scan.coverity.com/builds?project=cern-eos%2Feos
  tags:
    - coverity
  allow_failure: true
  only:
    - triggers

eos_periodic_sonar:
  stage: build:rpm
  script:
    - cppcheck -v --enable=all --inline-suppr --xml --xml-version=1 -i fst/layout/gf-complete -i common/sqlite  common/ fst/ mgm/ console/ fuse/ namespace/ mq/ 2> cppcheck-report.xml
    - sonar-scanner -Dsonar.host.url=http://sonar.cern.ch -Dsonar.cxx.cppcheck.reportPath=cppcheck-report.xml  -Dsonar.projectKey=eos:eos -Dsonar.projectName=eos -Dsonar.projectVersion="`./genversion.sh`" -Dsonar.sources=common/,fst/,mgm/,console/,fuse/,namespace/,mq/
  tags:
    - coverity
  allow_failure: true
  only:
    - triggers
